Skyscanner/applicationset-progressive-sync

README.md, api/v1alpha1/progressiverollout_types.go, api/v1alpha1/progressiverollout_types_test.go, controllers/progressiverollout_controller.go, controllers/progressiverollout_controller_test.go, go.mod, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/utils/consts.go, internal/utils/utils.go, internal/utils/utils_test.go
Fix #20
Notes:
- Fix local development instructions with kubebuilder
- Fix indentation in README
- Change the function name to `Owns`, because then when we read `pr.Owns(app.GetOwnersReference())` is clear that the Progressive Rollout owns the Application
- A scheduler that computes which applications we need to updated based on the stage parameters
- Scheduler tests
- New `utils` functions with their tests
- Updated the `should reconcile` integration test to work with the scheduler
=> Add scheduling logic

.github/workflows/release-artifacts.yaml, .github/workflows/test-build.yaml
Skyscanner doesn't have a public repository for Docker images when users can pull unauthenticated.
This is blocking https://github.com/Skyscanner/argocd-progressive-rollout/pull/34 as we can't test the Helm chart since we can't pull the docker image.
While we decide where to officially store our open source images, this PR push the docker image to my personal docker hub account. This was agreed internally as it's the fastest way to move forward with this ticket.
I'll raise a separate issue to point this to the official repository once we have one.
=> Temporary push artifacts to Docker Hub

.github/workflows/release-chart.yaml
Fix https://github.com/Skyscanner/argocd-progressive-rollout/pull/34 by
- using the correct chart directory
- publishing the chart when we merge into main
=> Publish helm chart on main

.github/workflows/release-chart.yaml
Fix https://github.com/Skyscanner/argocd-progressive-rollout/pull/37 by
- removing `charts_dir` since it already defaults to `charts` as per https://github.com/helm/chart-releaser-action/blob/master/cr.sh#L30
- fix `version` as it was missing a `v`
=> Fix helm release

.github/workflows/lint-test-chart.yaml, charts/argocd-progressive-rollout/Chart.yaml, charts/argocd-progressive-rollout/README.md, charts/argocd-progressive-rollout/ci/external-secret-values.yaml, charts/argocd-progressive-rollout/ci/external-secret.yaml, charts/argocd-progressive-rollout/ci/generated-secret-values.yaml, charts/argocd-progressive-rollout/ci/test-values.yaml, charts/argocd-progressive-rollout/templates/deployment.yaml, charts/argocd-progressive-rollout/templates/secret.yaml, charts/argocd-progressive-rollout/values.yaml, ct.yaml
We should allow users to reference an existing secret for fetching the operator configuration.
This option allows users to generate the secret in the way they want - using a controller, manually, etc. - without having to store the tokens as clear text in git.
=> Allow to reference an existing secret

controllers/progressiverollout_controller_test.go
Fix https://github.com/Skyscanner/argocd-progressive-rollout/issues/62
Because the k8s API server may not have finished creating the object after our `Create()` call from earlier, we use `Eventually()` testing function instead of `Expect()` to give the API server an opportunity to finish creating the object.
We also remove unnecessary `Create()` since when we call `requestsForApplicationChange` and `requestsForSecretChange` we pass the application and secret as parameter and they don't need to be on the API server.
=> Fix flaky test

controllers/progressiverollout_controller_test.go
The BeforeEach from the context relies on the BeforeEach on the describe
to be completed first;
We had an issue (#81) where this wasn't the case and resulting in
inconsistent testing (flaky).
Using JustBefore will make sure the Context setup will run after the
Describe.
https://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach
=> Fixing ginkgo Before race condition

controllers/progressivesync_controller_test.go, controllers/suite_test.go
- fixes #71 
- ensure that all objects/structs are created as their type, then referenced when used as per issue
=> Ensure objects are created in a consistent way without pointers

controllers/progressivesync_controller_test.go
This PR attempts to fix several race conditions that manifest in different ways:
#83, #81
I suspect this is coming from the use of `BeforeEach`, resetting the `namespace` name but being used later in the test.
It is a global scope, so by making it local I think we'll remove the issue.
=> Fix potential race condition and remove ambiguity with BeforeEach

charts/applicationset-progressive-sync/Chart.yaml
The crd definition has been renamed in #84 so we need to package a new chart that can install the correct crd definitions.
=> Release a new chart version

.github/workflows/code-quality.yaml
Running on schedule helps in early detection.
=> Run CodeQL on schedule

controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go
Fixes #67.
Two questions:
- I haven't touched `requestsForApplicationChange` nor `requestsForSecretChange` as they are called in `handler.EnqueueRequestsFromMapFunc(r.requestsForApplicationChange)` and `handler.EnqueueRequestsFromMapFunc(r.requestsForSecretChange)` respectively. Should we?
- I'm reusing the global `ctx` in tests - is there any better approach?
=> Reuse context in reconciler

api/v1alpha1/condition_types.go, config/crd/bases/argoproj.skyscanner.net_progressivesyncs.yaml, controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go, internal/scheduler/scheduler.go
=> Fix status update

.github/release-drafter.yml, .github/workflows/release-artifacts.yaml
Looking at the `Release Artifacts` it hasn't been running for a while. This PR:
- replace a third-party action with the docker one to extract metadata for tags. You can see it in action here: https://github.com/users/maruina/packages/container/package/docker-withings-sync (see `Recent tagged image versions`)
- use the git tag for the docker tag
- improve the release drafter template to leverage our issue labels
=> Fix release process

controllers/progressivesync_controller_test.go
... on #81.
It's fixed by keeping a local copy on the test scope, leaving no chance
for `namespace` to change in the process.
Begone, race condition of hell! 😈
=> Should fix the race condition once and for all

.github/workflows/release-artifacts.yaml
This reverts commit 0f054d603ec7a7606ad519689179d65729fad5c4.
Because of https://github.com/release-drafter/release-drafter/issues/876, the release drafter releases don't trigger the `push` event for GitHub. We tried to change it to trigger on `release` events, but then no tags are pushed, because it relies on `meta` information that seemingly doesn't exist for this event type (see https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/.github/workflows/release-artifacts.yaml#L36).
I'm reverting for now so we can push the tag manually, we'll investigate it later.
=> Revert "Update release-artifacts.yaml (#101)"

charts/applicationset-progressive-sync/Chart.yaml, charts/applicationset-progressive-sync/templates/rbac.yaml
Ref: Adding `update` and `patch` permissions to allow us to add the syncedAt annotation to the application object.
=> Add update and patch to the permissions

charts/applicationset-progressive-sync/Chart.yaml
Use chart version which is not present here: https://api.github.com/repos/Skyscanner/applicationset-progressive-sync/releases.
Background: At the moment, we seem to release a new chart using the latest tag on the repo, which is not good. I will add a task to fix this. For now, we can just use a chart number which doesn't exist yet.
=> Use chart version that doesn't exist

.github/workflows/release-artifacts.yaml
We got releases working off manual tags in #107, now let us try to restore the functionality of #101 which should allow us to get a new tagged image once release drafter has published the release.
=> Trigger image release on release being published

.github/workflows/test-build.yaml, Makefile, controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go, controllers/suite_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/utils/utils.go, internal/utils/utils_test.go
Fix #103 
- As discussed in #103 , the https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/controllers/progressivesync_controller_test.go#L268 test has a very naive ProgressiveSync object: two stages with a selector that returns only one cluster, and targeting a single cluster at the time.
We should change this test to better reflect a real case scenario. We've internally used as default the ProgressiveSync reported in #103 so this PR change the test to use that ProgressiveSync.
In addition, I changed a couple of helpers function to be more generic for when we want to add more tests with different combination of clusters.
**TODO**
This is a fork of #104 on commit cab8fff024c43a064ae7aab359f14caa14ff0f7a
=> Fix flaky CI with a complex test case

.github/workflows/release-artifacts.yaml
Aligns the version to be the same as in https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/.github/workflows/test-build.yaml#L62
=> Bumps build-push-action version in release-artifacts.yaml

controllers/progressivesync_controller_test.go, controllers/suite_test.go, main.go
Fix https://github.com/Skyscanner/applicationset-progressive-sync/issues/131
In the tests, I moved the Argo objects inside the `argocd` namespace and left the ProgressiveSync objects inside the random generated namespace. In this way we can test the controller watching multiple namespaces.
=> Multi namespace

controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/utils/state.go
- Adds logs to show more information when the stage is in an unknown state and when an application is changed.
- Fixes the logic inside the scheduler to account for all apps.
=> Add more logs and fix scheduler logic

charts/applicationset-progressive-sync/Chart.yaml, charts/applicationset-progressive-sync/README.md, charts/applicationset-progressive-sync/templates/deployment.yaml, charts/applicationset-progressive-sync/values.yaml
Update the chart to support the latest command options and `appVersion`.
Blocked by #130 and #132 .
=> Allow to specify controller and argocd namespaces

.github/workflows/test-build.yaml
Following the discussion [here](https://github.com/Skyscanner/applicationset-progressive-sync/pull/135#discussion_r709213929), we agreed that we should do this as a separate PR. Changed due to kubernetes-sigs/kubebuilder#2311
Updates the URL for downloading kubebuilder.
=> Fix the URL for downloading the kubebuilder

.github/workflows/test-build.yaml
Pushing an artifact for every PR breaks external contribution and dependabot, as we can see https://github.com/Skyscanner/applicationset-progressive-sync/runs/4522861353?check_suite_focus=true and https://github.com/Skyscanner/applicationset-progressive-sync/runs/4363099588?check_suite_focus=true
=> Don't push on PRs

charts/applicationset-progressive-sync/Chart.yaml, charts/applicationset-progressive-sync/templates/secret.yaml, charts/applicationset-progressive-sync/values.yaml, internal/consts/consts.go, internal/utils/argocd_client.go, internal/utils/config.go
hello! thanks for very useful argo extention!
Please consider following change:
allow to configure client plaintext connection, when applicationset-progressive-sync is running in the same cluster with argocd this will allow to use argocd svc as address `ARGOCD_SERVER_ADDR=argocd-server:80`
=> allow to configure client plaintext connection

controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go, controllers/suite_test.go, internal/utils/utils.go, internal/utils/utils_test.go
Fix an issue reported in https://github.com/Skyscanner/applicationset-progressive-sync/issues/147#issuecomment-1020074054
When the remote repository is updated, ArgoCD starts marking all the Applications pointing to it as `out of sync`.
This PR ensures the controller doesn't start until ArgoCD has updated all the Applications.
=> Ensure all the Applications have the same revision

api/v1alpha1/progressivesync_types.go, controllers/progressivesync_controller.go, controllers/progressivesync_controller_test.go
fix/workaround for https://github.com/Skyscanner/applicationset-progressive-sync/issues/146
basically the idea is to skip stage if targets returned empty list.
This also deserves a test but atm I do not have capacity for this :(
=> skip stage if no clusters were targeted

hack/dev/secrets.yml
Adding a comment to inform security researches that the ArgoCD secret used for CI
is not a password leakage on our behalf.
This is simply needed to bootstrap ArgoCD in a local environment and test the controller with
the full CRDs + app-progressive-sync.
=> Adding a comment on the ArgoCD secret
